### ISSUE TITLE
name of status in solution reporting of buses

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModelsRestoration.jl#17]
The status of a bus returned by 

https://github.com/lanl-ansi/PowerModelsRestoration.jl/blob/03bfe62d6484081987d3aa6056c97f27b0cce099/src/prob/rop.jl#L128

gives the dictionary key ["status"], rather than ["bus_type"]

This is an issue when taking solution data from one function to feed into another,  i.e.  mrsp status data -> rop

This was not caught previously because the cases for the PSCC paper did not use bus damage.

**Comment by noahrhodes** [comment]
@ccoffrin 

With the changes to building solutions, is it easier to wait to fix this?

**Comment by ccoffrin** [comment]
The `clean_status!` function should be called between runs and that should address this issue in the near term.  The changes in building solutions will not likely resolve this, so we should have a viable work around for the foreseeable future.  The issue that will resolve this once and for all is this one, https://github.com/lanl-ansi/PowerModels.jl/milestone/13

**Comment by noahrhodes** [comment]
Thanks!

**Comment by noahrhodes** [comment]
@noahrhodes verify that this can be closed with the updates in PM 0.15
