### ISSUE TITLE
Bug: solution builder fails for inactive buses

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModelsRestoration.jl#27]
If a bus has bus_type=4 (in active) it is removed by build_ref and a variable is not created for it.

Even if the connected loads have inactive status values, the solution builder searches for these components. It fails to find a component variable at that index and causes an error.

Code example:
``` 
using PowerModelsRestoration, Cbc
network_mld = parse_file("case5.m")
network_mld["bus"]["4"]["bus_type"] = 4
propagate_topology_status!(network_mld)
run_mld_strg(network_mld, DCPPowerModel, with_optimizer(Cbc.Optimizer))
```

@ccoffrin is this an issue with how add_solution! is being called from this package, or is it an issue with the function itself?

**Comment by ccoffrin** [comment]
Sounds like a bug in the solution builder to me.  This logic should be skipping all components with inactive status, `https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/solution.jl#L252` Maybe the arguments to `add_setpoint` for `status_name` and `inactive_status_value` in `solution_mld ` are not set correctly?

**Comment by noahrhodes** [comment]
The issue was that the status was not set correctly for loads, and storage.

the PowerModels function `propagate_topology_status!()` didn't set the status for storage devices ( https://github.com/lanl-ansi/PowerModels.jl/issues/662 )  This can be worked around for now.

Seperately, loads have a problem. I tried a new function in Restoration that would find damaged items and set their status to 0, but loads aren't currently don't have a damaged flag and `propagate_damaged_status!()` wouldn't add it.  Therefore, load status would remain active even if the connected bus was damaged.

So `build_ref()` will remove the load from the model because the bus it is attached to is inactive, however `build_solution()` will still try to get the variable for the item and cause an error


Should the fix be processing the input network data to clean the loads, or should it be in processing the solution?

**Comment by ccoffrin** [comment]
I think the fix should be part of how `ref` is populated.  The damage sets in ref should only include components that are also active (i.e. `status != 0`).  Based on my reading of the damage set code,

https://github.com/lanl-ansi/PowerModelsRestoration.jl/blob/master/src/core/ref.jl

I think that should be the case already.  So it is still a mystery to me why `build_solution` would be breaking in this case.

Also, I would not put much effort into fixing issues `build_solution` as this system will be replaced in the next 3-6 weeks.

**Comment by noahrhodes** [comment]
closed via https://github.com/lanl-ansi/PowerModels.jl/commit/7283960deb6246a7646b24bc9bc4f6f78ec7608f
