### ISSUE TITLE
What should be relaxed in run_rop versus run_rop_uc

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModelsRestoration.jl#3]
`run_rop_uc` enforces binary constraints on all indicator variables, for example load shedding and generation.  `run_rop` relaxes these to continuous variables between 0 and 1.

Therefore, when relaxed we have continuous load shedding but can also repair one generator 30% and another generator 70% in one time step.

Should this be allowed? which of the following should be relaxed for `run_rop`?
```
        _MLD.variable_bus_voltage_indicator(pm, nw=n, relax=true)
        variable_storage_damage_indicator(pm, nw=n, relax=true)
        variable_generation_damage_indicator(pm, nw=n, relax=true)
        _MLD.variable_demand_factor(pm, nw=n, relax=true)
        _MLD.variable_shunt_factor(pm, nw=n, relax=true)
```

@ccoffrin

**Comment by ccoffrin** [comment]
In the transmission context I would only make the loads relaxed and maybe shunts and I would collapse the `rop` and `roc_uc` formulations into one.

**Comment by noahrhodes** [comment]
Agreed
