### ISSUE TITLE
Bug: run_iterative_restoration does not returns improper data dictionary

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModelsRestoration.jl#33]
solution["data"] does not return the original data dictionary for the system.

**Comment by ccoffrin** [comment]
FYI, this will be address in the pms-v0.15 branch.

**Comment by noahrhodes** [comment]
this is more like I am return the wrong solution inside the algorithm.


I'll submit a fix tonight.

**Comment by ccoffrin** [comment]
Ok
