### ISSUE TITLE
Non-convex AC-MLD

### ISSUE THREAD

**Issue by Dx-Wang** [lanl-ansi/PowerModelsRestoration.jl#43]
I guess the `run_ac_mld_uc` solves the relaxed SOC-MLD formulation in your paper, right? Is there a way to solve the non-convex AC-MLD formulation with this package? Or is there another package for AC-MLD? Thanks!

**Comment by ccoffrin** [comment]
There are the examples of running the model with different formulations, https://github.com/lanl-ansi/PowerModelsRestoration.jl/blob/master/test/mld_uc.jl

The specifics of each formulation name can be found here, https://lanl-ansi.github.io/PowerModels.jl/stable/formulation-details/

The function `run_ac_mld_uc` is a heuristics approach that combines the SOC and AC MLD formulations to quickly find feasible solutions to the non-convex AC-MLD problem.  The implementation can be reviewed here, https://github.com/lanl-ansi/PowerModelsRestoration.jl/blob/master/src/util/ac-mld-uc.jl



I can also recomend having a look at the

**Comment by Dx-Wang** [comment]
Thanks a lot for your prompt response.

So the results I get from `run_ac_mld_uc` should be a solvable power flow case, right?

**Comment by ccoffrin** [comment]
Yes, as long as the termination status is reasonable the variable assignments should AC-PF feasible.  However, note that some components may be removed as part of the solution process, so you need to update the component status as indicated in the result's solution.

**Comment by Dx-Wang** [comment]
Thanks for pointing it out. Is calling `update_data!(model, result["solution"]);` sufficient for such updates?

**Comment by ccoffrin** [comment]
Yup!

**Comment by Dx-Wang** [comment]
Got it. Thanks a lot!
