### ISSUE TITLE
Iterative restoration - JuMP bug - DC formulation

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModelsRestoration.jl#49]
An issue in JuMP causes a constraint to fail when an iterator is empty. for example when there is no load in a time period of the Iterative restoration algorithm.

https://github.com/JuliaOpt/JuMP.jl/issues/2187.

Once this is fixed, restore the tests for the DC formulation of the Iterative Restoration problem.

**Comment by ccoffrin** [comment]
Can you send me an example?  The bug in JuMP was resolved some time ago, there might be another issue here.

**Comment by noahrhodes** [comment]
well...it works now, and I'm almost ready to make the pull request :)
