### ISSUE TITLE
Precompilation is broken due to `constraint_power_magnitude_sqr_on_off`

### ISSUE THREAD

**Issue by noahrhodes** [lanl-ansi/PowerModelsRestoration.jl#73]
the function `_PM.constraint_power_magnitude_sqr_on_off(pm::_PM.AbstractQCWRModel, n::Int, i, f_bus, arc_from, tm)` overwrite the PowerModels function by the same name, breaking precompilation.

However, QC is not currently a supported formulation for these problems, and has no test coverage.  This dead code breaks precompilation for no good reason.

**Comment by Robbybp** [comment]
Just hit this myself. Just noting here that adding `__precompile__(false)` to the top of the `PowerModelsRestoration.jl` file is another workaround.
